# Generated by Django 3.2.7 on 2021-10-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lexique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("langue1", models.CharField(max_length=20)),
                ("langue2", models.CharField(max_length=20)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lexon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mot1", models.CharField(max_length=40)),
                ("mot2", models.CharField(max_length=40)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "lexique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lexique.lexique",
                    ),
                ),
            ],
        ),
    ]
