# Generated by Django 3.2.12 on 2023-03-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0002_lexique_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexon',
            name='streak',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lexon',
            name='time_asked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
